export const GET_PAGES = "GET_PAGES";
export const GET_PAGE = "GET_PAGE";
export const ADD_PAGE = "ADD_PAGE";
export const DELETE_PAGE = "DELETE_PAGE";
export const PAGES_LOADING = "PAGES_LOADING";

export const GET_SEARCH_RESULT_WITH_GIVEN_SEARCHSTRING = "GET_SEARCH_RESULT_WITH_GIVEN_SEARCHSTRING";
export const SEARCH_RESULTS_LOADING = "SEARCH_RESULTS_LOADING"